---
# This file is used to set the words and port number

words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: 8020   # Select any available port if neither port nor server port are specified.
